services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
  avalanche:
    image: quay.io/prometheuscommunity/avalanche:main
    command: '--metric-count=${METRIC_COUNT} --series-count=10 --label-count=10 --series-interval=10000 --metric-interval=10000'
    depends_on:
      - cadvisor
  prom-agent:
    image: quay.io/prometheus/prometheus:main
    command: '--enable-feature=agent'
    ports:
      - 9090:9090
    security_opt:
      - label=disable
    volumes:
      - ./prom-agent.yml:/prometheus/prometheus.yml
    depends_on:
      - avalanche
    container_name: experiment
  prom-receiver:
    image: quay.io/prometheus/prometheus:main
    command: '--web.enable-remote-write-receiver'
    ports:
      - 9091:9090
    security_opt:
      - label=disable
    volumes:
      - ./prom-receiver.yml:/prometheus/prometheus.yml
    depends_on:
      - prom-agent
